### ISSUE TITLE
Invalid client

### ISSUE THREAD

**Issue by muhammetsahin** [ekmsystems/PartnerAuthDemo-csharp#1]
Hi there,

Im using your code just changed key and secret but im getting invalid client error ?

Your project screenshot:
![image](https://user-images.githubusercontent.com/2045788/48836376-a7715d00-ed93-11e8-89bf-985d217773eb.png)

And I've tried using your doc (https://docs.google.com/document/d/1Y26QJmrXi6NBID34E4M6G9D0_A-jLiNtGb9kHvGw69A/edit#)

Postman screenshot:
![image](https://user-images.githubusercontent.com/2045788/48836615-4433fa80-ed94-11e8-8de9-0581e488c3e1.png)

Where did i do wrong?
Thanks.

**Comment by ejcoyle88** [comment]
Hi @muhammetsahin,

It looks like your application isn't published in our [Partners Site](https://partners.ekm.net).
We don't currently have any kind of 'test mode', so all applications have to be published before they can access the API. Publishing doesn't make your application visible to any merchants, it's just a verification step that we have in place at the moment.

If you fill out all of the details for your application on the Partners site, it should let you click the Publish button. Once clicked someone on our side will verify the app and complete the process. Once that's done your keys should start working.

**Comment by ejcoyle88** [comment]
I'm going to update the README.md here (done in #2) to make that clear too, in case other people stumble upon this repo.

**Comment by muhammetsahin** [comment]
Great work! Thanks.
